Update post-refresh-steps.yml

diff --git a/.github/workflows/post-refresh-steps.yml b/.github/workflows/post-refresh-steps.yml
--- a/.github/workflows/post-refresh-steps.yml
+++ b/.github/workflows/post-refresh-steps.yml
@@ -67,7 +67,7 @@ jobs:
           echo "Running Apex script on org: ${{ env.ORGNAME }}"
           
           # Run the Apex script and capture the JSON output
-          OUTPUT=$(sf apex run --file ${GITHUB_WORKSPACE}/scripts/test1.apex --target-org ${{ env.ORGNAME }} --json || echo "$?")
+          OUTPUT=$(sf apex run --file ${GITHUB_WORKSPACE}/scripts/test1.apex --target-org ${{ env.ORGNAME }} --json || echo '{"status":"Failed"}')
           # Log the raw output for debugging purposes
           echo "Raw Apex run output: $OUTPUT"
                    
